title: Car Magazine
description: El mejor magazine que puedes encontrar en el mundo del automovilismo.
theme: just-the-docs
logo: "scania-scania-v8-logo.webp"
url: https://www.formula1.com/
nav_external_links:
  - title: Sonido de un V8 de Ferrari
    url: https://www.youtube.com/watch?v=5h67iFm7U7Q&pp=ygUSZmVycmFyaSBmMzU1IHNvdW5k
    hide_icon: false
    opens_in_new_tab: true
aux_links:
  Template Repository: https://en.wikipedia.org/wiki/Car
