title: Car Magazine
description: El mejor magazine que puedes encontrar en el mundo del automovilismo.
theme: just-the-docs
logo: "scania-scania-v8-logo.webp"
url: https://www.formula1.com/

aux_links:
  Template Repository: https://en.wikipedia.org/wiki/Car
